name: Deploying

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            pm2 stop personal-blog
            pm2 delete personal-blog
            cd /var/www/personal-blog-app
            git pull origin main
            npm install --prefix /var/www/personal-blog-app/api
            npm install --prefix /var/www/personal-blog-app/app
            cd /var/www/personal-blog-app/api
            npm run build
            pm2 start npm --name "personal-blog-api" --namespace "personal-blog" -- run "start"
            cd /var/www/personal-blog-app/app
            npm run build
            pm2 start npm --name "personal-blog-app" --namespace "personal-blog" -- run "start"
